exp_name: "'@{dataset.name}'_'@{network.name}'/s'@{seed}'"
output_dir: ./results/
save_output: True
merge_option: default # disabled if 'save_output' is False
mark: default # to mark the version of experiment
seed: 0

num_gpus: 1
num_workers: 0
num_machines: 1
machine_rank: 0


network:
  name: vgg19_32x32

dataset:
  name: cifar10
  root: ./data

ood_methods:
  - msp
  - odin
  - energy
  - mahalanobis
  - gradnorm
  - knn
  - react
  - vim
  - ash
  - dice
    

    
    
