ood_dataset:
  name: cifar10_ood_fc100
  num_classes: 10

  num_workers: '@{num_workers}'
  num_gpus: '@{num_gpus}'
  num_machines: '@{num_machines}'

  dataset_class: ImglistDataset
  batch_size: 128
  shuffle: False

  split_names: [val, nearood, farood]
  val:
    data_dir: ./data/images_classic/
    imglist_pth: ./data/benchmark_imglist/cifar10/val_tin.txt
  nearood:
    datasets: [cifar100, cifar100_full, tin]
    cifar100:
      data_dir: ./data/images_classic/
      imglist_pth: ./data/benchmark_imglist/cifar10/test_cifar100.txt
    cifar100_full:
      data_dir: ./data/images_classic/
      imglist_pth: ./data/benchmark_imglist/cifar10/test_cifar100_full.txt
    tin:
      data_dir: ./data/images_classic/
      imglist_pth: ./data/benchmark_imglist/cifar10/test_tin.txt
  farood:
    datasets: [mnist, svhn, texture, places365]
    mnist:
      data_dir: ./data/images_classic/
      imglist_pth: ./data/benchmark_imglist/cifar10/test_mnist.txt
    svhn:
      data_dir: ./data/images_classic/
      imglist_pth: ./data/benchmark_imglist/cifar10/test_svhn.txt
    texture:
      data_dir: ./data/images_classic/
      imglist_pth: ./data/benchmark_imglist/cifar10/test_texture.txt
    places365:
      data_dir: ./data/images_classic/
      imglist_pth: ./data/benchmark_imglist/cifar10/test_places365.txt
