postprocessor:
  name: debug
  APS_mode: False
  ft:
    epochs: 2
    beta: 1.
  padding:
    threshold: -1
  postprocessor_args:
    temperature: 100
    bogus: 42
  postprocessor_sweep:
    temperature_list: [100, 200]
    bogus_list: [42, 23]
