postprocessor:
  name: ft_dist
  APS_mode: False
  padding:
    threshold: 0.
  ft:
    epochs: 1000
    beta: 0.016
    unfreeze: penultimate
  postprocessor_args:
    mu_ood: zero
    gasless: True
    max_iterations_per_phase: True
